In [2]:
from splinter import Browser
from bs4 import BeautifulSoup
import requests
import pandas as pd
from sqlalchemy import create_engine

In [3]:
!which chromedriver

/usr/local/bin/chromedriver

In [3]:
executable_path = {'executable_path': '/usr/local/bin/chromedriver'}
browser = Browser('chrome', **executable_path, headless=False)

In [56]:
# URL of page to be scraped
url = 'https://screenrant.com/most-anticipated-movies-2017/'

# Retrieve page with the requests module
response = requests.get(url)
# Create BeautifulSoup object
soup = BeautifulSoup(response.text, 'html')

In [69]:
#scrape anticipated list for movie titles
movie_titles=[]
results= soup.find_all('div', class_= 'w-content')

for result in results:
    titles= result.find_all('h2')
for title in titles:
    name= title.text
    movie_titles.append(name)
movie_titles

['30. Jumanji',
 '29. King Arthur: Legend of the Sword',
 '28. Baywatch',
 '27. Kingsman: The Golden Circle',
 '26. The Mummy',
 '25. Transformers: The Last Knight',
 '24. Untitled Cloverfield Anthology Movie (God Particle)',
 '23. Coco',
 '22. Beauty and the Beast',
 '21. Baby Driver',
 '20. Ghost in the Shell',
 '19. The Fate of the Furious',
 '18. The Dark Tower',
 '17. Life',
 '16. Valerian and the City of a Thousand Planets',
 '15. Kong: Skull Island',
 '14. Power Rangers',
 '13. Dunkirk',
 '12. Blade Runner 2049',
 '11. John Wick: Chapter 2',
 '10. War for the Planet of the Apes',
 '9. Alien: Covenant',
 '8. The LEGO Batman Movie',
 '7. Thor: Ragnarok',
 '6. Spider-Man: Homecoming',
 '5. Logan',
 '4. Wonder Woman',
 '3. Justice League',
 '2. Guardians of the Galaxy Vol.2',
 '1. Star Wars: Episode VIII']

In [75]:
columns= {"Title": movie_titles}

In [77]:
movie_df= pd.DataFrame(columns)
movie_df

                                                Title
0                                         30. Jumanji
1                29. King Arthur: Legend of the Sword
2                                        28. Baywatch
3                     27. Kingsman: The Golden Circle
4                                       26. The Mummy
5                   25. Transformers: The Last Knight
6   24. Untitled Cloverfield Anthology Movie (God ...
7                                            23. Coco
8                            22. Beauty and the Beast
9                                     21. Baby Driver
10                             20. Ghost in the Shell
11                        19. The Fate of the Furious
12                                 18. The Dark Tower
13                                           17. Life
14    16. Valerian and the City of a Thousand Planets
15                             15. Kong: Skull Island
16                                  14. Power Rangers
17                                        13. Dunkirk
18                              12. Blade Runner 2049
19                           11. John Wick: Chapter 2
20                 10. War for the Planet of the Apes
21                                 9. Alien: Covenant
22                           8. The LEGO Batman Movie
23                                  7. Thor: Ragnarok
24                          6. Spider-Man: Homecoming
25                                           5. Logan
26                                    4. Wonder Woman
27                                  3. Justice League
28                   2. Guardians of the Galaxy Vol.2
29                         1. Star Wars: Episode VIII

In [82]:
movie_df["rank"], movie_df["title"] = movie_df["Title"].str.split(' ', 1).str
movie_df_final= movie_df[["rank", "title"]]
movie_df_final

   rank                                              title
0   30.                                            Jumanji
1   29.                   King Arthur: Legend of the Sword
2   28.                                           Baywatch
3   27.                        Kingsman: The Golden Circle
4   26.                                          The Mummy
5   25.                      Transformers: The Last Knight
6   24.  Untitled Cloverfield Anthology Movie (God Part...
7   23.                                               Coco
8   22.                               Beauty and the Beast
9   21.                                        Baby Driver
10  20.                                 Ghost in the Shell
11  19.                            The Fate of the Furious
12  18.                                     The Dark Tower
13  17.                                               Life
14  16.        Valerian and the City of a Thousand Planets
15  15.                                 Kong: Skull Island
16  14.                                      Power Rangers
17  13.                                            Dunkirk
18  12.                                  Blade Runner 2049
19  11.                               John Wick: Chapter 2
20  10.                     War for the Planet of the Apes
21   9.                                    Alien: Covenant
22   8.                              The LEGO Batman Movie
23   7.                                     Thor: Ragnarok
24   6.                             Spider-Man: Homecoming
25   5.                                              Logan
26   4.                                       Wonder Woman
27   3.                                     Justice League
28   2.                      Guardians of the Galaxy Vol.2
29   1.                            Star Wars: Episode VIII